core/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views
from .forms import LoginForm
app_name = 'core'

urlpatterns = [   
    path("", views.index, name = 'index'),
    path("dashboard/", views.dashboard, name='dashboard'),    
    path("donate/", views.Donatepage, name='donate'),    
    path('signup/', views.Signup, name='signup'),
    path('login/', LoginView.as_view(template_name='core/login.html', form_class=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

links/urls.py
from django.urls import path

from . import views

app_name = 'links'

urlpatterns = [
    path('', views.links, name = 'links'),
    path("<int:pk>/edit/", views.edit_link ,name ="edit_link"),
    path("<int:pk>/delete/", views.delete_link ,name ="delete_link"),
    path("create-link/", views.create_link ,name ="create_link"),
    path("categories/", views.categories, name = "categories"),
    path('categories/<int:pk>/edit/', views.edit_category, name = 'edit_category'),
    path('categories/<int:pk>/delete/', views.delete_category, name = 'delete_category'),
    path("categories/create-category/", views.create_category ,name ="create_category"),
]


saas/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('core.urls')),
    path("links/", include('links.urls')),
    path('admin/', admin.site.urls),

]

core/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    pass
 
class Donate(models.Model):
    name = models.CharField(max_length= 30)
    number = models.CharField(max_length=10)
    amount = models.IntegerField()
    order_id = models.CharField(max_length=70)

    def __str__(self):
        return f"{self.name} - {self.number} - {self.amount} - {self.order_id}"
    

links/models.py
from django.db import models
from core.models import User

class Category(models.Model):
    name = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name= "categories", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class Link(models.Model):
    category = models.ForeignKey(Category, related_name='links', on_delete = models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null = True)
    url = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='links', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created_at",)

core/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from .models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password',)

links/forms.py
from django import forms
from .models import Category, Link

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ('name',)


class LinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ('category','name','description', 'url',)


core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login
from links.models import Link
from .forms import SignupForm
import razorpay
from saas.settings import RAZORPAY_API_KEY, RAZORPAY_API_SECRET_KEY
from .models import Donate


@login_required
def dashboard(request):
    newest_links = Link.objects.filter(created_by = request.user)
    return render(request, "core/dashboard.html", {"newest_links": newest_links})


@login_required
def Donatepage(request):
    if request.method == "POST":
        name = request.POST.get('name')
        number = request.POST.get('number')
        amount = int(request.POST.get('amount'))
        
        order_amount = 100 * amount
        order_currency ="INR"
        client = razorpay.Client(auth=( RAZORPAY_API_KEY , RAZORPAY_API_SECRET_KEY ))
        payment_order = client.order.create(dict(amount = order_amount, currency = order_currency, payment_capture = 1 ))
        payment_order_id = payment_order["id"]
        donar = Donate(name = name, number = number, amount = amount, order_id = payment_order_id)
        donar.save()
        context = { "amount" : amount, "number": number, "name": name, "api_key": RAZORPAY_API_KEY, "order_id": payment_order_id , }
        return render(request, 'core/donate.html', context)
        # return redirect('/')

    return render(request, "core/donate.html")


def index(request):
    name = request.user.username
    return render(request, 'core/index.html', {'name': name})


def Signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            authenticate(username=user.username, password=user.password)
            if user is not None:
                login(request, user)
                return redirect('/')
    else:
        form = SignupForm()
    return render(request, 'core/signup.html', {
        'form': form
    })


links/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import CategoryForm, LinkForm
from .models import Category, Link


@login_required
def links(request):
    category = request.GET.get('category ', '')
    name = request.user.username
    links = Link.objects.filter(created_by=request.user)

    if category:
        links = links.filter(category_id=category)

    return render(request, 'links/links.html', {
        'links': links,
        'category': category,
        'name' : name,
    })

@login_required
def create_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        if form.is_valid():
            category = form.save(commit = False)
            category.created_by = request.user
            category.save()

            return redirect('/links/categories/')
    else: 
        form = CategoryForm()

    return render(request, 'links/create_category.html',{'form':form, 'title':'Create category',})


@login_required
def create_link(request):
    if request.method == 'POST':
        form = LinkForm(request.POST)

        if form.is_valid():
            link = form.save(commit = False)
            link.created_by = request.user
            link.save()

            return redirect('/dashboard/')
    else:
        form = LinkForm()
        form.fields['category'].queryset = Category.objects.filter(created_by = request.user)

    return render(request, 'links/create_link.html',{'form':form, 'title': 'Create Link'})


@login_required
def edit_link(request, pk):
    link = get_object_or_404(Link, created_by = request.user, pk = pk)

    if request.method == 'POST':
        form = LinkForm(request.POST, instance = link)

        if form.is_valid():
            form.save()

            return redirect('/links/')
    else:
        form = LinkForm(instance = link)
        form.fields['category'].queryset = Category.objects.filter(created_by = request.user)

    return render(request, 'links/create_link.html',{'form':form, 'title':"Edit Link"})


@login_required
def delete_link(request, pk):
    link = get_object_or_404(Link, created_by = request.user, pk=pk)
    link.delete()
    return redirect("/links/")


@login_required
def categories(request):
    categories = Category.objects.filter(created_by = request.user)
    return render(request, 'links/categories.html', {'categories':categories,})


@login_required
def edit_category(request, pk):
    category = get_object_or_404(Category, created_by = request.user, pk =pk)
    
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance = category)
        
        if form.is_valid():
            form.save()

            return redirect('/links/categories/')
    else:
        form = CategoryForm(instance = category)

    return render(request, 'links/create_category.html', {'form': form, 'title': 'Edit category',})


@login_required
def delete_category(request, pk):
    category = get_object_or_404(Category, created_by = request.user, pk =pk)
    category.delete()
    return redirect('/links/categories/')


core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> {%block title %} {% endblock %} | PROJECT</title>
        <script src = "https://cdn.tailwindcss.com"></script>         
        {% block additional_css %}{% endblock %}
    </head>
    <body class=bg-image>
        <nav class = "p-5 flex items-center justify-between bg-gray-800">
            <a class="text-2xl text-cyan-300" href = "/">PROJECT</a>
            <div class="space-x-3">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'core:donate' %}" class = "text-white">Donate</a>
                    <a href="{% url 'links:links' %}" class = "text-white">Links</a>
                    <a href="{% url 'links:categories' %}" class = " text-white " >Categories</a>
                    <a href="{% url 'core:dashboard' %}" class = "text-white">Dashboard</a>
                    <a href="{% url 'links:create_link' %}" class = "px-2 py-2 text-white bg-emerald-600 rounded-xl">Add Links</a>
                    <a href="{% url 'core:logout' %}" class = "px-2 py-2 text-white bg-rose-600 rounded-xl">Log Out</a>
                {% else %}
                    <a href="{% url 'core:signup'%}" class = "px-2 py-2 text-white bg-cyan-600 rounded-xl">Signup</a>
                    <a href="{% url 'core:login' %}" class = "px-2 py-2 text-white bg-gray-500 rounded-xl">Log In</a>
                {% endif %}
            </div>
        </nav>
        <main class = "flex-1 p-6">
            {% block content %}
            {% endblock %}
        </main>
        <footer class ="bg-gray-900 p-6">
            <center class = "text-xs text-gray-500">A SAAS application implemented by 
                <strong><a href = 'https://www.linkedin.com/in/saipraveenande/' target="_blank">Sai Praveen</a> </strong></center>
        </footer>
    </body>
</html>

core/templates/core/dashboard.html
{% extends "core/base.html" %}

{% block title %}Dashboard{% endblock %}
{% block additional_css %}
  {% load static%}
  <style>
    body{
        background-image: url("{% static 'images/img13.jpg' %}");
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        background-color: #1e2a38;
        background-position: center;
        background-size: cover;
        background-blend-mode: overlay;
        background-attachment: fixed;
        background-color: rgba(0, 0, 0, 0.3);
    }
  </style> 
{% endblock %}
{% block content %}
    <section class ='flex flex-col h-screen'>
        <h1 class ="mb-4 text-xl" >Dashboard</h1>
        <div class = "p-6 bg-gray-100 rounded-xl">
            <h2 class = "mb-4 text-xl">Newest links</h2>
            
            {% for link in newest_links %}
                <div class ="mb-2 flex justify-between items-center"> 
                    <p>{{ link.name }}</p>
                    <a href ="{{link.url}}" class = "underline" target = "_blank">Open link</a>
                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}


core/templates/core/donate.html
{% extends "core/base.html" %} {%block title%}Subscription{%endblock%}
{% block additional_css %}
  {% load static%}
  <style>
    body{
        background-image: url("{% static 'images/img18.jpg' %}");
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        background-color: #1e2a38;
        background-position: center;
        background-size: cover;
        background-blend-mode: overlay;
        background-attachment: fixed;
        background-color: rgba(0, 0, 0, 0.3);
    }
  </style> 
{% endblock %}
{%block content%}
  
<section class="flex flex-col h-screen">
    <div class="container px-4 py-8">
        <div class="mb-4 p-6 rounded-lg shadow-md">
            <div class=" shadow-md p-6 text-white rounded-xl">We are so excited to see you here! With your encouragement, we aim to offer more free tools to our users.</br></div>
            <h1 class="text-3xl font-bold mb-6">Contribute to the project</h1>
                
            <form action =".", method = "POST">
                {% csrf_token %}
                <input type="text" id="name" name="name" class=" px-3 py-2 border mb-5 rounded-lg bg-transparent focus:outline-none focus:ring focus:border-blue-300" placeholder="Enter Name" required> </br>
                <input type="number" id="number" name="number" class=" px-3 py-2 border mb-5 rounded-lg bg-transparent focus:outline-none focus:ring focus:border-blue-300" placeholder="Enter Number" required> </br>
                <input type="number" id="amount" name="amount" min="1" step="any" class=" px-3 bg-transparent py-2 mb-5 border rounded-lg focus:outline-none focus:ring focus:border-blue-300" placeholder="Enter amount" required>

                <button type="submit" id="rzp-button1" class="border-2 border-blue-300 text-blue-300 hover:text-white hover:bg-blue-300 font-bold py-2 px-4 rounded block">
                Donate
                </button>
            </form>
        </div>
    </div>
</section>


<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
var options = {
    "key": "{{ api_key }}", 
    "amount": "99900", 
    "currency": "INR",
    "name": "Thank you so much", 
    "description": "For SaaS app by Sai Praveen",
    "image": "https://example.com/your_logo",
    "order_id": "{{ order_id }}",
    "handler": function (response){
        alert(response.razorpay_payment_id);
       
    },
    "prefill": { 
        "name": "{{name}}", 
        "email": "", 
        "contact": "{{number}}" 
    },

    "theme": {
        "color": "#3399cc"
    }
};
var rzp1 = new Razorpay(options);
rzp1.on('payment.failed', function (response){
        alert(response.error.code);
        alert(response.error.description);
        alert(response.error.source);
        alert(response.error.step);
        alert(response.error.reason);
        alert(response.error.metadata.order_id);
        alert(response.error.metadata.payment_id);
});
document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    e.preventDefault();
}
</script>

{% endblock %}






core/templates/core/index.html
{% extends "core/base.html" %}

{%block title%}Welcome{%endblock%}
{% block additional_css %}
  {% load static%}
  <style>
    body{
        background-image: url("{% static 'images/img15.jpg' %}");
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        background-color: #1e2a38;
        background-position: center;
        background-size: cover;
        background-blend-mode: overlay;
        background-color: rgba(0, 0, 0, 0);
    }
  </style> 
{% endblock %}
{%block content%}
    <section class = 'flex justify-center items-center h-screen'> 
        <div class = 'text-center mx-auto'>
          <h1 class = 'text-6xl font-semibold'> Welcome {{name}}!</h1>
          <p class = 'font-light text-3xl mt-5'>Connect with world from here </br> by storing all your links with different categories.</p>
          <p class="text-gray-600 text-2xl mt-4">Organise all your social media and personal links.</p>
        </div>
    </section>
{% endblock%}

{% comment %} Organise all your links along with their description and categories at free of cost. You are one step away to organise all your social media and personal links. {% endcomment %}

core/templates/core/login.html
{% extends "core/base.html" %}

{% block title %}LogIn {% endblock %}
{% block additional_css %}
  {% load static%}
  <style>
    body{
        background-image: url("{% static 'images/img3.jpg' %}");
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        background-color: #1e2a38;
        background-position: center;
        background-size: cover;
        background-blend-mode: overlay;
        background-attachment: fixed;
        background-color: rgba(0, 0, 0, 0.3);
    }
  </style> 
{% endblock %}
{% block content %}
    <section class ='flex flex-col h-screen'>
        <div class="container mx-auto mt-8">
            <div class="max-w-md mx-auto bg-white rounded-lg shadow-lg p-8">
                <form method = "POST", action = ".">
                    {% csrf_token %}

                    {{ form.as_p }}

                    <button class = "mt-4 py-2 px-4 text-white bg-cyan-600 rounded-xl">Submit</button>
                </form> 

                <a href="{% url 'core:signup' %}" class='text-cyan-600' >Create Account</a>                
            </div>
        </div>
    </section>
{% endblock %}


core/templates/core/signup.html
{% extends "core/base.html" %}

{% block title %} Sign up {% endblock %}
{% block additional_css %}
  {% load static%}
  <style>
    body{
        background-image: url("{% static 'images/img3.2.jpg' %}");
        background-size: cover;
        background-repeat: no-repeat;
    }
  </style> 
{% endblock %}
{% block content %}
    <section class ='flex flex-col h-screen'>
        <div class="container mx-auto mt-8">
            <div class="max-w-md mx-auto bg-white rounded-lg shadow-lg p-8">
                <form method = "POST", action = ".">
                    {% csrf_token %}
            
                    {{ form.as_p }}
            
                    <button class = "mt-4 py-2 px-4 text-white bg-cyan-600 rounded-xl">Submit</button>
                </form> 
                <a href="{% url 'core:login' %}" class='text-cyan-600'>I have already account</a>
            </div>
        </div>
    </section>

{% endblock %} 

links/templates/links/categories.html
{% extends "core/base.html" %}

{% block title %}Categories{% endblock %}
{% block additional_css %}
  {% load static%}
  <style>
    body{
        background-image: url("{% static 'images/img13.jpg' %}");
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        background-color: #1e2a38;
        background-position: center;
        background-size: cover;
        background-blend-mode: overlay;
        background-attachment: fixed;
        background-color: rgba(0, 0, 0, 0.3);
    }
  </style> 
{% endblock %}
{% block content %}
    <section class ='flex-col h-screen'>
        <h1 class ="mb-4 text-3xl" >Categories</h1>
        <a class = "inline-block px-4 py-2 text-white mb-3 bg-cyan-600 rounded-xl" href="{% url 'links:create_category' %}">Create Category</a>

        <div class='grid grid-cols-3 gap-3 '>
            {% for category in categories %}
                <div class = "bg-white p-3 mb-3 rounded-xl">
                    <h2 class = 'mb-4 text-xl text-blue-900'>{{ category.name }}</h2>
                    
                    <a href = "{% url 'links:links' %}?category ={{ category.id }}" class="text-cyan-700">View</a> |
                    <a href = "{% url 'links:edit_category' category.id %}" class="text-cyan-700">Edit</a> |
                    <a href = "{% url 'links:delete_category' category.id %}" class="text-cyan-700">Delete</a>
                </div>
            {% endfor %}
        </div>
    </section>   
{% endblock %}


links/templates/links/create_category.html
{% extends "core/base.html" %}

{% block title %}{{title}} {% endblock %}
 {% block additional_css %}
  {% load static%}
  <style>
    body{
        background-image: url("{% static 'images/img17.jpg' %}");
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        background-color: #1e2a38;
        background-position: center;
        background-size: cover;
        background-blend-mode: overlay;
        background-color: rgba(0, 0, 0, 0.3);
    }
  </style> 
{% endblock %} 
{% block content %}
    <section class ='flex flex-col h-screen'>
        <div class="container mx-auto mt-8">
            <div class="max-w-md mx-auto bg-white rounded-lg p-8">

                <h1 class ="text-3xl mb-4" >{{ title}}</h1>
                <form method = "POST", action = ".">
                    {% csrf_token %}
        
                    {{ form.as_p }}
        
                    <button class = "mt-4 py-2 px-4 text-white bg-cyan-600 rounded-xl">Submit</button>
                </form>

            </div>
        </div> 
    </section>
{% endblock %}


links/templates/links/create_link.html
{% extends "core/base.html" %}

{% block title %}{{title}}{% endblock %}
{% block additional_css %}
  {% load static%}
  <style>
    body{
        background-image: url("{% static 'images/img17.jpg' %}");
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        background-color: #1e2a38;
        background-position: center;
        background-size: cover;
        background-blend-mode: overlay;
        background-color: rgba(0, 0, 0, 0.3);
    }
  </style> 
{% endblock %}
{% block content %}
    <section class ='flex flex-col h-screen'>

        <div class="container mx-auto mt-8">
            <div class="max-w-md mx-auto bg-white rounded-lg shadow-lg p-8">

                <h1 class ="mb-4 text-3xl" >{{title}}</h1>
       
                    <form method = "POST", action = ".">
                        {% csrf_token %}

                        {{ form.as_p }}

                        <button class = "mt-4 py-2 px-4 text-white bg-cyan-600 rounded-xl">Submit</button>
                    </form>
            </div>
        </div>
    </section>
{% endblock %}


links/templates/links/links.html
{% extends "core/base.html" %}

{% block title %}Links{% endblock %}

{% block additional_css %}
{% load static %}
<style>
    body{
        background-image: url("{% static 'images/img13.jpg' %}");
        display: flex;
        flex-direction: column;
        min-height: 100vh;
        background-color: #1e2a38;
        background-position: center;
        background-size: cover;
        background-blend-mode: overlay;
        background-attachment: fixed;
        background-color: rgba(0, 0, 0, 0.3);
    }
    .btn{
        border: 1px solid #666;
        border-radius: 20px;
        cursor: pointer;
        padding: 8px 22px;
        position: relative;
    }
    .btn:hover{
        background-color: #34495E;
        border: 1px solid #34495E;
        color: #EBEDEF;
    }
    .special{
        background-color: #34495E;
        border: 1px solid #34495E;
        color: #EBEDEF;
    }
    #buton.highlight {
        background-color: #34495E;
        border: 1px solid #34495E;
        color: #EBEDEF;
      }
</style>
{% endblock %}

{% block content %}
    <section class ='flex flex-col h-screen'>
        <h1 class ="mb-4 text-3xl" >Links</h1>
        <div id = 'mydiv' class='mb-6 space-x-6 space-y-6'>
            {% for category in request.user.categories.all %}
                <a id = 'buton' class = 'btn' href ="{% url 'links:links' %}?category ={{ category.id }}">{{category.name}}</a>           
            {% endfor %}
        </div>
        <div class="grid grid-cols-3 gap-3">
            {% for link in links %}
                <div class="bg-gray-100 p-6 rounded-xl">
                    <h2 class="mb-4 text-xl">{{ link.name }}</h2>

                    {% if link.description %}
                        <p class="mb-4 text-xs">{{ link.description }}</p>
                    {% endif %}

                    <a href="{{ link.url }}" class="text-cyan-700" target="_blank">Open link</a>
                    |
                    <a href="{% url 'links:edit_link' link.id %}" class="text-cyan-700">Edit</a>
                    |
                    <a href="{% url 'links:delete_link' link.id %}" class="text-cyan-700">Delete</a>
                </div>
            {% empty %}
                <div class="bg-gray-100 p-6 rounded-xl">Hi {{name}}, currently you don't have any links for this category... </br> <a class='text-cyan-900 text-xl' href="{% url 'links:create_link' %}"> Add links</a></div>
            {% endfor %}
        </div>        
    </section>
{% endblock %}

{% block additional_script %}
  <script>
    const buttons = document.querySelectorAll('buton');

    function handleClick(event) {
      const clickedButton = event.target;
      buttons.forEach((button) => button.classList.remove('highlight'));
      clickedButton.classList.add('highlight');
    }
    buttons.forEach((button) => {
      button.addEventListener('click', handleClick);
    });
  </script> 
{% endblock %}